name: Firebase CD

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Create environment file
        run: |
          cd src
          cd environments
          echo export const environment = \{production:true,emailServiceId:\"${{ secrets.emailServiceId }}\",emailTemplateId:\"${{ secrets.emailTemplateId }}\",emailUserId:\"${{ secrets.emailUserId }}\",firebaseConfig:\"${{ secrets.FIREBASE_WEB_CONFIG }}\"\} > environment.production.ts
          cat environment.production.ts
      - run: npm install
      - run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
